import {Box, Inputs, Button, SmartTable} from 'adminlte-2-react';
import { useState } from 'react';


function CommentHistory() {
    const [data, setData] = useState(Array(8).fill(Array(3).fill(null)));
    const tableData = [
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'},
        { time: '07/12/2023 12:21 PM', name: 'jane doe', comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla accumsan purus id imperdiet bibendum. Nunc convallis nibh eget nisi rhoncus, sodales placerat turpis pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam condimentum porttitor convallis. Ut porta tristique nisl vitae malesuada. Duis euismod ante imperdiet ipsum mollis, vitae interdum velit ultrices. Suspendisse vel faucibus libero, id suscipit ligula. Aenean placerat a orci ac dictum. Etiam vitae ex id ante sollicitudin ultricies nec in augue.'},
        { time: '07/11/2023 10:11 AM', name: 'john doe', comment: 'In cursus posuere arcu, ac vehicula lorem mollis sed. Praesent urna sapien, semper vitae enim rutrum, tincidunt scelerisque purus. Ut nec lorem massa. Etiam in dictum ipsum. Etiam mollis feugiat lorem eget ultricies. Maecenas vel justo eros. Nullam aliquam risus at neque eleifend, vitae lobortis augue pharetra. Phasellus mollis felis a mi auctor varius. Etiam nisi dolor, rutrum in massa a, pellentesque sodales diam. Nulla facilisi. Maecenas accumsan enim nec ligula tempus euismod. Aenean vestibulum purus mauris, quis luctus urna interdum eu. Suspendisse lobortis ex ac lorem tempor, bibendum ornare lorem tempor. Phasellus sed justo sit amet ex vehicula tincidunt. Aliquam et orci quis enim blandit venenatis et quis metus. Aliquam at molestie justo.'}
    ];

    const tableColumns = [
        { title: 'Time',    data: 'time'    },
        { title: 'Name',    data: 'name',    width:"11rem"},
        { title: 'Comment', data: 'comment' },
    ];

    return(
        <Box title="Comment History">
            <SmartTable
                data={tableData}
                columns={tableColumns}
            />

        </Box>
    )
}

export default CommentHistory;